CREATE TABLE item(
	ItemId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ItemUniqueKey VARCHAR(100) NOT NULL UNIQUE,
	ItemName VARCHAR(250) NOT NULL
);
CREATE TABLE category(
	categoryId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	categoryName VARCHAR(250) NOT NULL
);
CREATE TABLE itemCategory(
	itemCategoryId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ItemId SMALLINT UNSIGNED ,
	categoryId SMALLINT UNSIGNED,
	FOREIGN KEY(ItemId) REFERENCES item(itemId),
	FOREIGN KEY(categoryId) REFERENCES category(categoryId)
);
CREATE TABLE measuringUnit(
	measuringUnitId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	measuringUnitName VARCHAR(50) NOT NULL
);
CREATE TABLE itemMeasuringUnit(
	itemMeasuringUnitId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ItemId SMALLINT UNSIGNED ,
	measuringUnitId SMALLINT UNSIGNED,
	isValid BOOLEAN DEFAULT 1,
	FOREIGN KEY(ItemId) REFERENCES item(itemId),
	FOREIGN KEY(measuringUnitId) REFERENCES measuringUnit(measuringUnitId)
);
CREATE TABLE itemPriceChart(
	itemPriceChartId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	itemMeasuringUnitId SMALLINT UNSIGNED,
	qty FLOAT UNSIGNED NOT NULL,
	price FLOAT UNSIGNED NOT NULL,
	FOREIGN KEY(itemMeasuringUnitId) REFERENCES itemMeasuringUnit(itemMeasuringUnitId)
);
CREATE TABLE CustOrder(
	CustOrderId INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	CustOrderNum VARCHAR(50) NOT NULL,
	CustOrderDate DATETIME NOT NULL,
	OrderForDate DATETIME NOT NULL,
	discount FLOAT,
	tax FLOAT
);
CREATE TABLE offer(
	offerId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	discountRate FLOAT UNSIGNED NOT NULL,
	offerName VARCHAR(50) NOT NULL,
	validFrom DATE NOT NULL,
	validTill DATE NOT NULL
);
CREATE TABLE offerItem(
	offerItemId SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	offerId SMALLINT UNSIGNED,
	itemId SMALLINT UNSIGNED,
	FOREIGN KEY(offerId) REFERENCES offer(offerId),
	FOREIGN KEY(itemId) REFERENCES item(itemId)
);
CREATE TABLE CustOrderItems(
	CustOrderItemsId INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	CustOrderId INT UNSIGNED,
	itemId SMALLINT UNSIGNED,
	measuringUnitId SMALLINT UNSIGNED,
	qty FLOAT UNSIGNED NOT NULL,
	offerIdAvailed SMALLINT UNSIGNED,
	modifiedPricePerUnit FLOAT UNSIGNED,
	FOREIGN KEY(itemId) REFERENCES item(itemId),
	FOREIGN KEY(measuringUnitId) REFERENCES measuringUnit(measuringUnitId),
	FOREIGN KEY(CustOrderId) REFERENCES CustOrder(CustOrderId),
	FOREIGN KEY(offerIdAvailed) REFERENCES offer(offerId)
);
ALTER TABLE item ADD COLUMN isvalid BOOLEAN DEFAULT 1;
ALTER TABLE item ADD COLUMN isavailable BOOLEAN DEFAULT 1;